package com.example.techtest.termfrequency.stream;

/**
 * Interface to be implemented by basic stream components capable of read,
 * process and generate some specific entities
 * 
 * @author dmacia
 *
 * @param <I> the type of entities consumed by the component
 * @param <O> the type of entities generated by the component
 */
public interface Processor<I, O> extends Sink<I>, Source<O> {

}
