package com.example.techtest.termfrequency.stream;

import java.util.concurrent.BlockingQueue;

/**
 * Interface to be implemented by basic stream components capable of produce
 * some specific entities
 * 
 * @author dmacia
 *
 * @param <E> the type of entities generated by the component
 */
public interface Source<E> {

	/**
	 * Define the queue the entities are produced to
	 * 
	 * @param queue
	 */
	public void output(BlockingQueue<E> queue);
}
